name: qlcode-chat

services:
  qlcode-chat:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
      args:
        HTTP_PROXY: ${HTTP_PROXY:-}
        HTTPS_PROXY: ${HTTPS_PROXY:-}
        ALL_PROXY: ${ALL_PROXY:-}
        NO_PROXY: ${NO_PROXY:-localhost,127.0.0.1}
        http_proxy: ${HTTP_PROXY:-}
        https_proxy: ${HTTPS_PROXY:-}
        all_proxy: ${ALL_PROXY:-}
        no_proxy: ${NO_PROXY:-localhost,127.0.0.1}
    image: qlcode-chat:${QLCODE_CHAT_DOCKER_TAG:-v0.9.6}
    container_name: qlcode-chat
    volumes:
      - qlcode-chat:/app/backend/data
    ports:
      - ${QLCODE_CHAT_PORT-3000}:8080
    environment:
      - WEBUI_SECRET_KEY=${QLCODE_CHAT_SECRET_KEY:-}
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  qlcode-chat: {}
